version: "3.9"

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - finanz-net

  airflow-init:
    image: apache/airflow:2.6.2
    container_name: airflow-init
    depends_on:
      - postgres
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
    entrypoint: /bin/bash
    command:
      - -c
      - |
        echo "⏳ Waiting for Postgres..."
        until pg_isready -h postgres -p 5432 -U airflow; do
          sleep 2;
        done
        echo "✅ Postgres ready. Initializing Airflow..."
        airflow db reset -y
        airflow db init
        airflow users create \
          --username admin \
          --firstname Admin \
          --lastname User \
          --role Admin \
          --email admin@example.com \
          --password admin
    networks:
      - finanz-net
    volumes:
      - ./dags:/opt/airflow/dags
      - ./dags/data:/opt/airflow/dags/data

  airflow-webserver:
    image: apache/airflow:2.6.2
    container_name: airflow-webserver
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
    ports:
      - "8080:8080"
    command: webserver
    networks:
      - finanz-net
    volumes:
      - ./dags:/opt/airflow/dags
      - ./dags/data:/opt/airflow/dags/data

  airflow-scheduler:
    image: apache/airflow:2.6.2
    container_name: airflow-scheduler
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
    command: scheduler
    networks:
      - finanz-net
    volumes:
      - ./dags:/opt/airflow/dags
      - ./dags/data:/opt/airflow/dags/data

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: dashboard
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    networks:
      - finanz-net
    volumes:
      - ./dashboard:/app

volumes:
  postgres_data:

networks:
  finanz-net:
